from turtle import *

my_turtle = Turtle()
my_turtle.speed(100)
my_turtle.screen.setup(1200, 800)

# Нарисовать квадрат
def draw_rect(t):
    for x in range(0, 4):
        t.right(90)
        t.forward(10)


def fox(t):
    t.left(90)
    t.forward(10)
    t.left(90)
    t.forward(10)
    t.right(90)
    t.forward(60)
    t.right(90)
    t.forward(10)
    t.right(90)
    t.forward(10)
    t.left(90)
    t.forward(10)
    t.right(90)
    t.forward(10)
    t.left(90)
    t.forward(20)
    t.left(90)
    t.forward(10)
    t.right(90)
    t.forward(10)
    t.left(90)
    t.forward(10)
    t.right(90)
    t.forward(10)
    t.right(90)
    t.forward(60)
    t.right(90)
    t.forward(10)
    t.left(90)
    t.forward(10)
    t.left(90)
    t.forward(10)
    t.right(90)
    t.forward(20)
    t.left(90)
    t.forward(10)
    t.right(90)
    t.forward(20)
    t.left(90)
    t.forward(10)
    t.left(90)
    t.forward(30)
    t.left(90)
    t.forward(10)
    t.right(90)
    t.forward(60)
    t.right(90)
    t.forward(10)
    t.left(90)
    t.forward(10)
    t.right(90)
    t.forward(10)
    t.left(90)
    t.forward(10)
    t.right(90)
    t.forward(10)
    t.right(90)
    t.forward(20)
    t.left(90)
    t.forward(10)
    t.right(90)
    t.forward(10)
    t.left(90)
    t.forward(10)
    t.right(90)
    t.forward(70)
    t.right(90)
    t.forward(10)
    t.left(90)
    t.forward(10)
    t.right(90)
    t.forward(10)
    t.left(90)
    t.forward(10)
    t.right(90)
    t.forward(70)
    t.right(90)
    t.forward(50)
    t.left(90)
    t.forward(20)

    t.up()
    t.right(90)
    t.forward(30)
    t.down()
    draw_rect(t)

    t.up()
    t.right(90)
    t.forward(40)
    t.down()
    draw_rect(t)

    t.up()
    t.right(90)
    t.forward(30)
    t.right(90)
    t.forward(30)       
    t.down()
    draw_rect(t)

    t.up()
    t.forward(60)
  

fox(my_turtle)

# Необходимо, чтобы окно не закрывалось само, а только по клику
my_turtle.screen.exitonclick()
my_turtle.screen.mainloop()
